### ISSUE TITLE
Error: This dependency was not found

### ISSUE THREAD

**Issue by Klemen1337** [stonega/vue2-boring-avatars#1] opened 2021-06-08 09:10 UTC
Hi! 👋 
Great job with the vue2 port, just what I needed. But when I try to use it I am constantly getting 'dependency was not found' error. Yes I ran the `npm install --save vue2-boring-avatars` command 😄 

Cheers,
K

```
 ERROR  Failed to compile with 1 error 

This dependency was not found:

* vue2-boring-avatars in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Details.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save vue2-boring-avatars
```

**Comment by agustif** [comment] 2021-06-22 20:28
Same issue

**Comment by agustif** [comment] 2021-06-22 22:03
You can try https://www.npmjs.com/package/@schpnpls/vue2-boring-avatars until #2 gets merged into main!

Working for me =-), in case it may take a while, I will delete my package once this one is working!

**Closed as completed** 2021-06-23 01:19 UTC

**Comment by stonega** [comment] 2021-06-23 07:57
@agustif Thanks for the pr, the issue has been fixed.

**Comment by agustif** [comment] 2021-06-23 08:34
@stonega No problem! Thank you for the hard work of porting the lib! Glad to help with a small thing.

Btw, I'm having some issues with some variants like beam or marble, should I open issues for it?

**Comment by stonega** [comment] 2021-06-23 11:33
> @stonega No problem! Thank you for the hard work of porting the lib! Glad to help with a small thing.
> 
> Btw, I'm having some issues with some variants like beam or marble, should I open issues for it?

Sure, please open a new issue

**Comment by agustif** [comment] 2021-06-23 13:09
> > @stonega No problem! Thank you for the hard work of porting the lib! Glad to help with a small thing.
> > Btw, I'm having some issues with some variants like beam or marble, should I open issues for it?
> 
> Sure, please open a new issue

It seems it's not a bug on the library, but some interaction with my css, I cannot reproduce it on a clean project, there it looks alright!

https://codesandbox.io/s/nuxt-2-with-vite-forked-igqxi?file=/pages/index.vue

I need to debug further, maybe my tailwindcss is interacting with the svg, I don't get the masks to work properly so they are not circles in beam
